# Generated by Django 4.2.4 on 2023-08-28 11:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_new_sees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
    ]
